### ISSUE TITLE
Open Forest and SUDS permit cleanup

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-middlelayer-api#241]
## Notes
Ensure that the dev database for both open forest special uses and SUDS are cleaned up in order to perform testing from a clean slate.

## Tasks
- [ ] Remove applications from "Pending" in Staging
- [ ] Reach out to Xin to have her remove those applications from the dev db ins SUDS
- [ ] Verify that those applications were removed
- [ ] PO approved

**Comment by Dmac26** [comment]
@mwreiss - I wanted to make sure everything was kosher before I went back to Xin. I wasn't able to actually delete those applications from "Pending" but I was able to reject them. The were all moved to "Rejected". Is that what you meant? I don't believe we have a deleted function built in.
