### ISSUE TITLE
Update our logic to check for a duplicate name when and application is submitted and then skip "contcn" if it is duplicate

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-middlelayer-api#242]
## Notes
Recently we have noticed a change in the way our application interacts with the SUDS database, making it impossible to accept an application to SUDS on the special-uses platform if the name on the application currently being submitted is a duplicate from a previous application. Since we have a number of applicants who need permits annually this will need to be remedied.

According to Xin on the SUDS team we will need to identify where in our logic we are communicating with SUDS to assign a value to the "contact cn" field, write a loop to check for duplicate applicant names, and if the name already exists, get the "contact cn" for that name and assign it to the new applications contact cn field instead of generating a new one

## Tasks
- [ ] Determine whether or not all of the logic that needs to implemented to check for and assign "contact cn" can all be done on our end
- [ ] Write all necessary logic
- [ ] Test locally
- [ ] Push to Dev
- [ ] Validate in dev
- [ ] Push to Prod
- [ ] Validate in Prod
- [ ] PO approved
