### ISSUE TITLE
Troubleshoot and fix api connection from staging to SUDS

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-middlelayer-api#243]
## Notes
Currently, users signed in as an admin are unable to "accept" applications and submit them to SUDS. When an attempt is made users are presented with the below error:

![submitToSudsErrorGUI.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/52b747ec-5f51-4f50-a24c-bd3e0bb053f1)

.... and the error in the console:

![submitToSudsErrorConsole.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/fb479be3-77e2-45b4-a299-73ea82f803a5)

## Tasks
- [ ] Reach out to Arvind to see if any certificates have been changed
- [ ] If Arvind cannot provid the fix reach out to Mike
- [ ] Troubleshoot to understand why applications cannot be submitted to SUDS
- [ ] Apply necessary fix
- [ ] PO approved

## Definition of Done
- [ ] Users can once again accept applications to SUDS from staging
- [ ] Usability tested
